on:
  release:
    types: [published]

jobs:
  get-info:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - uses: actions/checkout@v2
      - run: ruby -r ./newfile.rb
