on:
  issues:
    types: [edited]

jobs:
  testing:
    name: issue edited
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "edit on issue: $ISSUE"
        env:
          ISSUE: ${{ github.event.issue.number }}
      - uses: actions/github-script@v6
        with:
          script: |
            const tasks = github.event
            console.log(tasks)
