on:
  issues:
    types: [edited]

jobs:
  testing:
    name: issue edited
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/github-script@v6
        with:
          script: |
            //console.log(context)
            const issueNumber = context.payload.issue.number
            console.log(issueNumber)
            const sender = context.payload.sender.login
            const tasksBefore = context.payload.changes.body.from.match(/(- \[[x\s]\].+)/g)
            const tasksAfter = context.payload.issue.body.match(/(- \[[x\s]\].+)/g)

            if(!tasksAfter){
              console.log("No tasks list were found")
              return
            }
            
            const updatedTasks = []
            for(let task of tasksAfter) {
              if (!tasksBefore) {
                task.includes("[x]") ? console.log("checked") : console.log("not checked")
                continue
                
              } else if(!tasksBefore.includes(task)) {
                console.log("includes")
                let taskStatus = task.includes("[x]") ? "complete" : "incomplete"
                // timestamp??
                updatedTasks.push(`@${sender} marked the checklist item *${task.split("]")[1].trim()}* as ${taskStatus}`)
              }
            }
            console.log(updatedTasks)
            console.log("finish")
            
