on:
  issues:
    types: [edited]

jobs:
  testing:
    name: issue edited
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo edit on issue: $ISSUE
          echo event sender: ${{ github.event.sender }}
          echo event changes: ${{ github.event.changes }}
        env:
          ISSUE: ${{ github.event.issue.number }}
