on:
  issues:
    types: [edited]

jobs:
  testing:
    name: issue edited
    runs-on: ubuntu-latest
    steps: 
      - run: |
          cat << OBJECT
          $ {{ toJson(github) }}
          OBJECT
        env:
          ISSUE: ${{ github.event.issue.number }}
