on:
  issues:
    types: [edited]

jobs:
  testing:
    name: issue edited
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "edit on issue: $ISSUE"
        env:
          ISSUE: ${{ github.event.issue.number }}
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.changes.body.from + "\n")
            console.log(context.payload.issue.body)
            console.log("sender: " + context.payload.sender.login)
            const tasksBefore = context.payload.changes.body.from.match(/(- \[[x\s]\].+)/g)
            const tasksAfter = context.payload.issue.body.match(/(- \[[x\s]\].+)/g)
            for(let task of tasksBefore) {
              console.log(task);
            }
