on:
  issues:
    types: [edited]

jobs:
  testing:
    name: issue edited
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo "edit on issue: $ISSUE"
          echo "sender: ${{ github.event.sender }}"
        env:
          ISSUE: ${{ github.event.issue.number }}
