on:
  issues:
    types: [edited]

jobs:
  testing:
    name: issue edited
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNum = context.payload.issue.number;
            nodeId = context.payload.issue.node_id;
            const sender = context.payload.sender.login;
            const tasksBefore = context.payload.changes.body.from.match(/(- \[[x\s]\].+)/g);
            const tasksAfter = context.payload.issue.body.match(/(- \[[x\s]\].+)/g);

            if(!tasksAfter){ return; }
            
            var updatedTask = "";
            for(let task of tasksAfter) {
              if (!tasksBefore) { 
                continue;
              } else if(!tasksBefore.includes(task)) {
                let taskStatus = task.includes("[x]") ? "complete" : "incomplete";
                updatedTask = (`@${sender} marked the checklist item **${task.split("]")[1].trim()}** as ${taskStatus}`);
              }
            }
            
            if(updatedTask.length == 0){ return; }
            console.log(updatedTask.length)
            console.log("Updated task: " + updatedTask);
            const { repo: { owner, repo }  } = context;
            github.rest.issues.createComment({ issue_number: issueNum, owner, repo, body: updatedTask });
