on:
  release:
    types: [published]

jobs:
  justajob:
    runs-on: ubuntu-latest
    steps:
      - name: this workflow should call test.rb
        uses: Go-Go-Power-Rangers/test-action@main
        id: test-script
        with: 
          test: "Hello there"
